### ISSUE TITLE
Error on logout (v1.4.1)

### ISSUE THREAD

**Issue by cbriant1** [Satergo/Satergo#12] opened 2022-09-07 12:41 UTC
I get an error when clicking logout. Also seems to hang for a while or completely freeze when selecting menu options. No problems when running v.0.0.2
![Capture](https://user-images.githubusercontent.com/97860766/188880479-ac8f5ad4-204b-4c39-98ed-a5f9584a098b.JPG)

**Comment by satsen** [comment] 2022-09-07 19:44
Which version is this and can you copy the full error because unfortunately this image is not useful at all. Also, which menu & which options cause a freeze, did these issue appear as soon as you updated.

**Comment by cbriant1** [comment] 2022-09-07 21:26
The version is 1.4.1 the older version 0.0.2 is working fine. It started as soon as I upgraded to 1.4.1  I've attached as much of the error message I could when logging out. It never completes the logout so I have to cancel the program. It seems that when I click on Transactions is when it freezes with not responding and after waiting for a while I just have to cancel the program.
[Error Message.txt](https://github.com/Satergo/Satergo/files/9516803/Error.Message.txt)

**Comment by satsen** [comment] 2022-09-07 21:39
Oh no, one line of code from a currently ongoing complete revamp of the UI design got mixed into the 1.4.1 release so it is trying to access a file that was not moved in 1.4.1 but was in the redesign. An unfortunate mistake and you will have to close the wallet to log out until the next release is out. Sorry for this.

Not sure what is going on with the Transactions tab though. Does it happen all the time? There isn't actually any code run when the tab is changed to Transactions so I'm not sure what the cause could be.

**Comment by cbriant1** [comment] 2022-09-08 01:03
yes after doing a little more testing, it seems to happen when clicking the Transactions button. The program will freeze, and I have to click X to cancel, and I get the following message.
![Clipboard01](https://user-images.githubusercontent.com/97860766/189011165-bd1ed1c3-09ca-418b-94fc-4d8ed005f28c.jpg)

**Comment by satsen** [comment] 2022-09-08 20:13
@cbriant1 Thanks, I will have to check this.

**Comment by satsen** [comment] 2022-12-24 18:15
Fixed in 1.5.0. I have no idea what the freezing is, can you try the new version? Perhaps it got fixed.

**Closed as completed by satsen** 2022-12-24 18:15 UTC
Labels: bug

**Comment by satsen** [comment] 2023-04-30 21:01
@cbriant1 I found the case of the freezing. You probably received the Mi Goreng airdrop, or a similar meaningless coin. In Mi Goreng's case, there are 15002 outputs that Satergo is trying to render somehow, so that freezes it. I will check it out.

**Comment by satsen** [comment] 2023-04-30 22:24
The issue with the transactions tab freezing has been solved. It will be out in the next update
